# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0003_statedemographics_universitydatacollegedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydatacollegedata',
            name='female',
            field=models.DecimalField(blank=True, db_column='Female', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='universitydatacollegedata',
            name='male',
            field=models.DecimalField(blank=True, db_column='Male', decimal_places=2, max_digits=15, null=True),
        ),
    ]
