# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Colleges', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
