# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('timesent', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contactform',
            },
        ),
    ]
