# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('time_sent', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'contactform',
            },
        ),
    ]
