# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Georgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=34, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=13, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('size', models.IntegerField(blank=True, db_column='Size', null=True)),
                ('amer_indian', models.DecimalField(blank=True, db_column='Amer_Indian', decimal_places=1, max_digits=2, null=True)),
                ('african_amer', models.DecimalField(blank=True, db_column='African_Amer', decimal_places=1, max_digits=3, null=True)),
                ('asian_pac_is', models.DecimalField(blank=True, db_column='Asian_Pac_Is', decimal_places=1, max_digits=3, null=True)),
                ('hispanic', models.DecimalField(blank=True, db_column='Hispanic', decimal_places=1, max_digits=3, null=True)),
                ('international', models.DecimalField(blank=True, db_column='International', decimal_places=1, max_digits=3, null=True)),
                ('white', models.DecimalField(blank=True, db_column='White', decimal_places=1, max_digits=3, null=True)),
                ('multi_race_not_hispanic_latino', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('unknown', models.DecimalField(blank=True, db_column='Unknown', decimal_places=1, max_digits=2, null=True)),
                ('women', models.DecimalField(blank=True, db_column='Women', decimal_places=1, max_digits=3, null=True)),
                ('men', models.DecimalField(blank=True, db_column='Men', decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Georgia',
                'managed': False,
            },
        ),
    ]
